# Generated by Django 3.0.2 on 2020-01-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorski', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnici',
            name='email',
            field=models.EmailField(default='test.test@test.com', max_length=255, unique=True),
        ),
    ]
