# Generated by Django 3.0.2 on 2020-01-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorski', '0002_korisnici_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnici',
            name='role',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('Student', 'Student')], default='Student', max_length=7),
        ),
    ]
